### ISSUE TITLE
[São José dos Campos] Desenvolvedor Full Stack na Beedoo

### ISSUE THREAD

**Issue by lucasxciv** [PHPVale/vagas#4]
## Descrição da vaga

A Beedoo Software contrata Desenvolvedor.

## Local

São José dos Campos ou São Paulo

## Requisitos

**Desejáveis:**
- PHP (Framework Codeigniter);
- Javascript;
- JQuery;
- CSS;
- HTML;
- MySQL;
- Controle de versão (Git, Tortoise);

**Diferenciais:**
- Vue.js;
- Experiência com Infra AWS (EC2, RDS);

## Contratação

CLT ou PJ

## Como se candidatar

Envie seu CV para daniel.lima@beedoo.com.br.
Caso possua, envie o perfil do Linkedin e Github também!

###### Divulgação solicitado por: [Rodrigo Mafra](https://www.facebook.com/rodrigo.mafra.52)

**Comment by heliomsolivas** [comment]
Enviado! 👍
